[DEVHAS-339] Remove resource limits
devfile-samples/devfile-sample-python-basic pull request #24
Opened 2023-05-11 19:27 UTC by michael-valdron

# What does this PR do?

Removes the resource limits from the devfile and `deploy.yaml` kubernetes deploy spec to ensure compatibility to the Red Hat Hybrid Application Console when setting the resource requests.

In addition, the resource requests defined in the devfile has now been added to `deploy.yaml` in preparation for deprecating the `attribute` fields shared between the two files.

2023-05-12 02:22 UTC, maysunfaisal requested changes

2023-05-12 02:22 UTC, maysunfaisal commented on deploy.yaml
> +          resource:
resources instead of resource?

2023-05-23 20:58 UTC, elsony approved these changes
/lgtm

2023-05-31 22:57 UTC, maysunfaisal approved these changes

2023-06-01 00:45 UTC, merged